---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: signalingenvelopes.wice.riasc.eu
spec:
  scope: Namespaced
  group: wice.riasc.eu
  names:
    kind: SignalingEnvelope
    plural: signalingenvelopes
    singular: signalingenvelope
    shortNames:
    - env
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            contents:
              type: object
              properties:
                nonce:
                  type: string
                  description: Base64-encoded nonce
                  pattern: '^[A-Za-z0-9+/]+={0,2}$'
                body:
                  type: string
                  description: Base64-encoded encrypted message body
                  pattern: '^[A-Za-z0-9+/]+={0,2}$'
            recipient:
              type: string
              description: Base64-encoded public key of the recipient
              pattern: '^[A-Za-z0-9+/]+={0,2}$'
            sender:
              type: string
              description: Base64-encoded public key of the sender
              pattern: '^[A-Za-z0-9+/]+={0,2}$'
                