# SPDX-FileCopyrightText: 2023-2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

run:
  exclude-files:
  - ".*\\.pb\\.go$"
  - ".*_grpc\\.pb\\.go$"

issues:
  exclude-rules:
  - path: 'cmd/(.+)'
    linters:
    - forbidigo
  - path: '(.+)_test\.go'
    linters:
    - gochecknoglobals
  - path: '(.+)_test\.go'
    linters:
    - revive
    text: dot-imports
    source: (ginkgo|gomega)
  - path: 'test/(.+)'
    text: do not define dynamic errors, use wrapped static errors instead

linters-settings:
  misspell:
    locale: US

  exhaustive:
    default-signifies-exhaustive: true

  gomodguard:
    blocked:
      modules:
      - github.com/pkg/errors:
          recommendations:
          - errors

  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
        xml: snake

  gci:
    sections:
    - standard
    - default
    - prefix(cunicu.li/cunicu)
    - blank
    - dot

    custom-order: true

linters:
  enable-all: true

  disable:
  - cyclop
  - depguard
  - exhaustruct
  - funlen
  - gocyclo
  - godox
  - ireturn
  - lll
  - mnd
  - nestif
  - nolintlint
  - nonamedreturns
  - paralleltest
  - protogetter
  - tagalign
  - tenv
  - varnamelen
  - wrapcheck
