---
project_name: wice

before:
  hooks:
  - go mod tidy
  - go generate ./...

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Signing is disabled here as we can not perform it in the CI
# Its is expected that the maintainer adds the checksum.asc file to the release by hand
# after the CI pipeline has created the release.
# signs:
# - artifacts: checksum
#   signature: "${artifact}.asc"
#   cmd: gpg
#   args: ["-u", "09BE3BAE8D55D4CD8579285A9675EAC34897E6E2", "--output", "${signature}", "--detach-sign", "${artifact}"]

builds:
- id: wice
  main: ./cmd/wice
  binary: wice
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - freebsd
  - windows

  goarch:
  - amd64
  - arm64
  - arm
  
  goarm:
  - "7"

  ignore:
  - goos: windows
    goarch: arm

  ldflags:
  - -s -w
  - -X github.com/stv0g/cunicu/pkg/util/buildinfo.Version={{.Version}}
  - -X github.com/stv0g/cunicu/pkg/util/buildinfo.Commit={{.Commit}}
  - -X github.com/stv0g/cunicu/pkg/util/buildinfo.Date={{.Date}}
  - -X github.com/stv0g/cunicu/pkg/util/buildinfo.Tag={{.Tag}}
  - -X github.com/stv0g/cunicu/pkg/util/buildinfo.Branch={{.Branch}}
  - -X github.com/stv0g/cunicu/pkg/util/buildinfo.BuiltBy=GoReleaser

archives:
- builds:
  - wice

  # https://goreleaser.com/customization/archive/#packaging-only-the-binaries
  files:
  - none*

  format: gz

  format_overrides:
  - goos: windows
    format: zip

nfpms:
- vendor: stv0g
  homepage: https://github.com/stv0g/wice/
  maintainer: Steffen Vogel <post@steffenvogel.de>
  license: Apache 2.0

  formats:
  - apk
  - deb
  - rpm

  recommends:
  - wireguard-tools

  contents:
  - src: "./etc/systemd/wice.service"
    dst: "/usr/lib/systemd/system/wice.service"
  - src: "./etc/wice.yaml"
    dst: "/etc/wice.yaml"
    type: config
  - src: "./docs/usage/man/*.3"
    dst: "/usr/share/man/man3"

dockers:
- use: buildx
  dockerfile: Dockerfile.scratch
  goos: linux
  goarch: amd64
  image_templates:
  - "ghcr.io/stv0g/{{ .ProjectName }}:latest-amd64"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}-amd64"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

- use: buildx
  dockerfile: Dockerfile.scratch
  goos: linux
  goarch: arm64
  image_templates:
  - "ghcr.io/stv0g/{{ .ProjectName }}:latest-arm64v8"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}-arm64v8"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64v8"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

- use: buildx
  dockerfile: Dockerfile.scratch
  goos: linux
  goarch: arm
  goarm: "7"
  image_templates:
  - "ghcr.io/stv0g/{{ .ProjectName }}:latest-armv7"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}-armv7"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-armv7"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
  build_flag_templates:
  - --platform=linux/arm/v7
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/stv0g/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
- name_template: "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Version }}"
  image_templates:
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Version }}-armv7"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Version }}-arm64v8"
- name_template: "ghcr.io/stv0g/{{ .ProjectName }}:latest"
  image_templates:
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Version }}-amd64"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Version }}-armv7"
  - "ghcr.io/stv0g/{{ .ProjectName }}:v{{ .Version }}-arm64v8"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

publishers:
- name: Gemfury
  cmd: >-
    bash -c "
      if [[ ${ARTIFACT_PATH} == *.rpm || ${ARTIFACT_PATH} == *.deb || ${ARTIFACT_PATH} == *.apk ]]; then
        curl -F package=@${ARTIFACT_PATH} https://${GEMFURY_TOKEN}@push.fury.io/wice/
      fi
    "
  env:
  - GEMFURY_TOKEN={{ .Env.GEMFURY_TOKEN }}
  - ARTIFACT_PATH={{ .ArtifactPath }}

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: stv0g
    name: wice

  draft:  true
  prerelease: auto