/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	wicev1 "github.com/stv0g/cunicu/pkg/signaling/k8s/apis/wice/v1"
	versioned "github.com/stv0g/cunicu/pkg/signaling/k8s/client/clientset/versioned"
	internalinterfaces "github.com/stv0g/cunicu/pkg/signaling/k8s/client/informers/externalversions/internalinterfaces"
	v1 "github.com/stv0g/cunicu/pkg/signaling/k8s/client/listers/wice/v1"
)

// SignalingEnvelopeInformer provides access to a shared informer and lister for
// SignalingEnvelopes.
type SignalingEnvelopeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.SignalingEnvelopeLister
}

type signalingEnvelopeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSignalingEnvelopeInformer constructs a new informer for SignalingEnvelope type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSignalingEnvelopeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSignalingEnvelopeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSignalingEnvelopeInformer constructs a new informer for SignalingEnvelope type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSignalingEnvelopeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WiceV1().SignalingEnvelopes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WiceV1().SignalingEnvelopes(namespace).Watch(context.TODO(), options)
			},
		},
		&wicev1.SignalingEnvelope{},
		resyncPeriod,
		indexers,
	)
}

func (f *signalingEnvelopeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSignalingEnvelopeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *signalingEnvelopeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&wicev1.SignalingEnvelope{}, f.defaultInformer)
}

func (f *signalingEnvelopeInformer) Lister() v1.SignalingEnvelopeLister {
	return v1.NewSignalingEnvelopeLister(f.Informer().GetIndexer())
}
