package p2p

import (
	"github.com/ipfs/go-cid"
	"github.com/multiformats/go-multihash"
	"riasc.eu/wice/pkg/crypto"
)

// publicKeyToCid generates a Cid from a public X25519 key
// The Cid is generated by hashing the public key with SHA256
// This avoids putting the real public keys into the DHT.
func publicKeyToCid(key *crypto.Key) cid.Cid {
	pref := cid.Prefix{
		Version: 1,
		Codec:   cid.Raw,
		MhType:  multihash.SHA2_256,
	}

	c, _ := pref.Sum(key[:])

	return c
}
