.nh
.TH "cunīcu" "1" "Oct 2022" "https://github.com/stv0g/cunicu" ""

.SH NAME
.PP
cunicu-version - Show version of the cunīcu binary and optionally also a running daemon


.SH SYNOPSIS
.PP
\fBcunicu version [flags]\fP


.SH DESCRIPTION
.PP
Show version of the cunīcu binary and optionally also a running daemon


.SH OPTIONS
.PP
\fB-f\fP, \fB--format\fP="human"
	Output \fB\fCformat\fR (one of: human, json)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for version

.PP
\fB-s\fP, \fB--short\fP[=false]
	Only show version and nothing else


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)

.PP
\fB-v\fP, \fB--verbose\fP=0
	verbosity level


.SH EXAMPLE
.PP
.RS

.nf
$ sudo cunicu version
client: v0.1.2 (os=linux, arch=arm64, commit=b22ee3e7, branch=master, built-at=2022-09-09T13:44:22+02:00, built-by=goreleaser)
daemon: v0.1.2 (os=linux, arch=arm64, commit=b22ee3e7, branch=master, built-at=2022-09-09T13:44:22+02:00, built-by=goreleaser)

.fi
.RE


.SH SEE ALSO
.PP
\fBcunicu(1)\fP
