.nh
.TH "cunīcu" "1" "Oct 2022" "https://github.com/stv0g/cunicu" ""

.SH NAME
.PP
cunicu-wg-genkey - Generates a random private key in base64 and prints it to standard output.


.SH SYNOPSIS
.PP
\fBcunicu wg genkey [flags]\fP


.SH DESCRIPTION
.PP
Generates a random private key in base64 and prints it to standard output.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for genkey


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)

.PP
\fB-v\fP, \fB--verbose\fP=0
	verbosity level


.SH SEE ALSO
.PP
\fBcunicu-wg(1)\fP
