.nh
.TH "cunicu" "3" "Sep 2022" "https://github.com/stv0g/cunicu" ""

.SH NAME
.PP
cunicu - cunicu


.SH SYNOPSIS
.PP
\fBcunicu [flags]\fP


.SH DESCRIPTION
.PP
WireGuard Interactive Connectivity Establishment


.SH OPTIONS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)

.PP
\fB-v\fP, \fB--verbose\fP=0
	verbosity level

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for cunicu


.SH SEE ALSO
.PP
\fBcunicu-completion(3)\fP, \fBcunicu-config(3)\fP, \fBcunicu-daemon(3)\fP, \fBcunicu-monitor(3)\fP, \fBcunicu-restart(3)\fP, \fBcunicu-self-update(3)\fP, \fBcunicu-signal(3)\fP, \fBcunicu-status(3)\fP, \fBcunicu-stop(3)\fP, \fBcunicu-sync(3)\fP, \fBcunicu-version(3)\fP, \fBcunicu-wg(3)\fP
