.nh
.TH "cunīcu" "1" "Oct 2022" "https://github.com/stv0g/cunicu" ""

.SH NAME
.PP
cunicu-wg - WireGuard commands


.SH SYNOPSIS
.PP
\fBcunicu wg [flags]\fP


.SH DESCRIPTION
.PP
The wg sub-command mimics the wg(8) commands of the wireguard-tools package.
In contrast to the wg(8) command, the cunico sub-command delegates it tasks to a running cunucu daemon.

.PP
Currently, only a subset of the wg(8) are supported.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for wg


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-q\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)

.PP
\fB-v\fP, \fB--verbose\fP=0
	verbosity level


.SH SEE ALSO
.PP
\fBcunicu(1)\fP, \fBcunicu-wg-genkey(1)\fP, \fBcunicu-wg-genpsk(1)\fP, \fBcunicu-wg-pubkey(1)\fP, \fBcunicu-wg-show(1)\fP, \fBcunicu-wg-showconf(1)\fP
