.nh
.TH "cunīcu" "1" "Oct 2022" "https://github.com/stv0g/cunicu" ""

.SH NAME
.PP
cunicu-wg-pubkey - Calculates a public key and prints it in base64 to standard output.


.SH SYNOPSIS
.PP
\fBcunicu wg pubkey [flags]\fP


.SH DESCRIPTION
.PP
Calculates a public key and prints it in base64 to standard output from a corresponding private key (generated with genkey) given in base64 on standard input.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for pubkey


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)

.PP
\fB-v\fP, \fB--verbose\fP=0
	verbosity level


.SH EXAMPLE
.PP
.RS

.nf
# A private key and a corresponding public key may be generated at once by calling:
$ umask 077
$ wg genkey | tee private.key | wg pubkey > public.key

.fi
.RE


.SH SEE ALSO
.PP
\fBcunicu-wg(1)\fP
