.nh
.TH "cunīcu" "1" "Oct 2022" "https://github.com/stv0g/cunicu" ""

.SH NAME
.PP
cunicu-completion-powershell - Generate the autocompletion script for powershell


.SH SYNOPSIS
.PP
\fBcunicu completion powershell [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for powershell.

.PP
To load completions in your current shell session:

.PP
.RS

.nf
cunicu completion powershell | Out-String | Invoke-Expression

.fi
.RE

.PP
To load completions for every new session, add the output of the above command
to your powershell profile.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for powershell

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)

.PP
\fB-v\fP, \fB--verbose\fP=0
	verbosity level


.SH SEE ALSO
.PP
\fBcunicu-completion(1)\fP
