.nh
.TH "WICE" "3" "Feb 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice - WICE


.SH SYNOPSIS
.PP
\fBwice [flags]\fP


.SH DESCRIPTION
.PP
Wireguard Interactive Connectitivty Establishment


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for wice

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of "debug", "info", "warn", "error", "dpanic", "panic", and "fatal")


.SH SEE ALSO
.PP
\fBwice-completion(3)\fP, \fBwice-daemon(3)\fP, \fBwice-monitor(3)\fP, \fBwice-signal(3)\fP, \fBwice-stop(3)\fP, \fBwice-sync(3)\fP, \fBwice-wg(3)\fP
