.nh
.TH "WICE" "3" "Feb 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-stop - Shutdown the WICE daemon


.SH SYNOPSIS
.PP
\fBwice stop [flags]\fP


.SH DESCRIPTION
.PP
Shutdown the WICE daemon


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for stop

.PP
\fB-s\fP, \fB--socket\fP="/var/run/wice.sock"
	Unix control and monitoring socket


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of "debug", "info", "warn", "error", "dpanic", "panic", and "fatal")


.SH SEE ALSO
.PP
\fBwice(3)\fP
