.nh
.TH "WICE" "3" "Feb 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-docs - Generate documentation for the wice commands


.SH SYNOPSIS
.PP
\fBwice docs [flags]\fP


.SH DESCRIPTION
.PP
Generate documentation for the wice commands


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for docs

.PP
\fB--output-dir\fP="./docs/usage"
	Output directory of generated documenation


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of "debug", "info", "warn", "error", "dpanic", "panic", and "fatal")


.SH SEE ALSO
.PP
\fBwice(3)\fP, \fBwice-docs-man(3)\fP, \fBwice-docs-markdown(3)\fP
