.nh
.TH "ɯice" "3" "Aug 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-completion-zsh - Generate the autocompletion script for zsh


.SH SYNOPSIS
.PP
\fBwice completion zsh [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for the zsh shell.

.PP
If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:

.PP
.RS

.nf
echo "autoload -U compinit; compinit" >> ~/.zshrc

.fi
.RE

.PP
To load completions in your current shell session:

.PP
.RS

.nf
source <(wice completion zsh); compdef _wice wice

.fi
.RE

.PP
To load completions for every new session, execute once:

.SS Linux:
.PP
.RS

.nf
wice completion zsh > "${fpath[1]}/_wice"

.fi
.RE

.SS macOS:
.PP
.RS

.nf
wice completion zsh > $(brew --prefix)/share/zsh/site-functions/_wice

.fi
.RE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for zsh

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)


.SH SEE ALSO
.PP
\fBwice-completion(3)\fP
