.nh
.TH "WICE" "3" "Feb 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-docs-markdown - Generate markdown docs


.SH SYNOPSIS
.PP
\fBwice docs markdown [flags]\fP


.SH DESCRIPTION
.PP
Generate markdown docs


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for markdown


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of "debug", "info", "warn", "error", "dpanic", "panic", and "fatal")

.PP
\fB--output-dir\fP="./docs/usage"
	Output directory of generated documenation


.SH SEE ALSO
.PP
\fBwice-docs(3)\fP
