.nh
.TH "ɯice" "3" "Sep 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-monitor - Monitor the ɯice daemon for events


.SH SYNOPSIS
.PP
\fBwice monitor [flags]\fP


.SH DESCRIPTION
.PP
Monitor the ɯice daemon for events


.SH OPTIONS
.PP
\fB-f\fP, \fB--format\fP="human"
	Output \fB\fCformat\fR (one of: json, logger, human)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for monitor

.PP
\fB-s\fP, \fB--rpc-socket\fP="/var/run/wice.sock"
	Unix control and monitoring socket


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)


.SH SEE ALSO
.PP
\fBwice(3)\fP
