.nh
.TH "cunicu" "3" "Sep 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice - cunicu


.SH SYNOPSIS
.PP
\fBwice [flags]\fP


.SH DESCRIPTION
.PP
WireGuard Interactive Connectivity Establishment


.SH OPTIONS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for wice


.SH SEE ALSO
.PP
\fBwice-completion(3)\fP, \fBwice-daemon(3)\fP, \fBwice-monitor(3)\fP, \fBwice-restart(3)\fP, \fBwice-self-update(3)\fP, \fBwice-signal(3)\fP, \fBwice-status(3)\fP, \fBwice-stop(3)\fP, \fBwice-sync(3)\fP, \fBwice-version(3)\fP, \fBwice-wg(3)\fP
