.nh
.TH "ɯice" "3" "Aug 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-completion-fish - Generate the autocompletion script for fish


.SH SYNOPSIS
.PP
\fBwice completion fish [flags]\fP


.SH DESCRIPTION
.PP
Generate the autocompletion script for the fish shell.

.PP
To load completions in your current shell session:

.PP
.RS

.nf
wice completion fish | source

.fi
.RE

.PP
To load completions for every new session, execute once:

.PP
.RS

.nf
wice completion fish > ~/.config/fish/completions/wice.fish

.fi
.RE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for fish

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)


.SH SEE ALSO
.PP
\fBwice-completion(3)\fP
