.nh
.TH "ɯice" "3" "Sep 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-wg - WireGuard commands


.SH SYNOPSIS
.PP
\fBwice wg [flags]\fP


.SH DESCRIPTION
.PP
WireGuard commands


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for wg


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)


.SH SEE ALSO
.PP
\fBwice(3)\fP, \fBwice-wg-genkey(3)\fP, \fBwice-wg-genpsk(3)\fP, \fBwice-wg-pubkey(3)\fP, \fBwice-wg-show(3)\fP, \fBwice-wg-showconf(3)\fP
