.nh
.TH "ɯice" "3" "Sep 2022" "https://github.com/stv0g/wice" ""

.SH NAME
.PP
wice-version - Show current status of the ɯice daemon, its interfaces and peers


.SH SYNOPSIS
.PP
\fBwice version [flags]\fP


.SH DESCRIPTION
.PP
Show current status of the ɯice daemon, its interfaces and peers


.SH OPTIONS
.PP
\fB-f\fP, \fB--format\fP="human"
	Output \fB\fCformat\fR (one of: human, json)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for version


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB-C\fP, \fB--color\fP="auto"
	Enable colorization of output (one of: auto, always, never)

.PP
\fB-l\fP, \fB--log-file\fP=""
	path of a file to write logs to

.PP
\fB-d\fP, \fB--log-level\fP="info"
	log level (one of: debug, info, warn, error, dpanic, panic, and fatal)


.SH SEE ALSO
.PP
\fBwice(3)\fP
