# SPDX-FileCopyrightText: 2023-2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Compliance Checks

on:
  push:
    branches:
    - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reuse:
    uses: cunicu/.github/.github/workflows/reuse.yaml@v0.3.0

  flake:
    name: Check flake.lock
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v9
      with:
        fail-mode: true
        send-statistics: false
